# -*- coding: utf-8 -*-
"""MNIST-Tensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ip-usgtV1zwBUD-ODulQJUkTE5_LuR62
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Load MNIST
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

# 2. Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# 3. Build Model
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10)
])

# 4. Compile
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

# 5. Train
model.fit(x_train, y_train, epochs=5)

# 6. Predict
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# 7. Confusion Matrix
cm = confusion_matrix(y_test, y_pred_classes)

# 8. Plot
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix for MNIST (Keras Model)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# 6. Evaluate the model (inbuilt test loop)
model.evaluate(x_test, y_test)

