# -*- coding: utf-8 -*-
"""MNIST-CNN-Tensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHGzXEZAAXrUvOc3aMfKHTbAIcVM1ivO
"""

import tensorflow as tf
from tensorflow.keras import layers, models, datasets
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test  = x_test.reshape(-1, 28, 28, 1) / 255.0

model = models.Sequential([
    layers.Input(shape=(28,28,1)),

    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10)                      # logits (no softmax)
])

model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=5, batch_size=64)

model.evaluate(x_test, y_test)

y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

cm = confusion_matrix(y_test, y_pred_classes)

plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - CNN (Keras)")
plt.show()

# Pick first 6 test images
sample_images = x_test[:6]
sample_labels = y_test[:6]

# Predict
predictions = model.predict(sample_images)
pred_classes = np.argmax(predictions, axis=1)

plt.figure(figsize=(9,4))
for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(sample_images[i].reshape(28,28), cmap='gray')
    plt.title(f"True: {sample_labels[i]}, Pred: {pred_classes[i]}")
    plt.axis("off")

plt.tight_layout()
plt.show()

