# -*- coding: utf-8 -*-
"""Linear Regression 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jlDBWCAsoo1ptUFcYGzW16lAmKLeraT
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 1. Load CSV
df = pd.read_csv("student-mat.csv", sep=';')

# 2. Select useful features
X = df[['G1', 'G2', 'studytime', 'failures', 'absences']]
y = df['G3']  # final grade

print("Dataset shape:", df.shape)
print(df.head())

# 3. Train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Create and train model
model = LinearRegression()
model.fit(X_train, y_train)

# 5. Predict
y_pred = model.predict(X_test)

# 6. Evaluate
print("MSE:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

# 7. Plot predicted vs actual
plt.scatter(y_test, y_pred, color='blue')
plt.xlabel("Actual Final Grade (G3)")
plt.ylabel("Predicted Final Grade")
plt.title("Actual vs Predicted Grades")
plt.show()

# 8. Print learned coefficients
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

